/**
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, version 2.1, dated February 1999.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the latest version of the GNU Lesser General
 * Public License as published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program (LICENSE.txt); if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Based on code generated by Agitar build: Agitator Version 1.0.2.000071 (Build date: Jan 12, 2007) [1.0.2.000071]
 */
package org.jamwiki.utils;

import junit.framework.TestCase;

public class TiddlyWiki2MediaWikiTranslatorTest extends TestCase {

	/*
	// FIXME - failing, re-enabled later
	public void testHeader() throws Exception {
		TiddlyWiki2MediaWikiTranslator t = new TiddlyWiki2MediaWikiTranslator();
		assertEquals("=test=", t.translate("!test"));
		assertEquals("==test==", t.translate("!!test"));
		assertEquals("===test===", t.translate("!!!test"));
		assertEquals("=test=\n=test2=", t.translate("!test\n!test2"));
	}
	*/
	/*
	// FIXME - failing, re-enabled later
	public void testTables() throws Exception {
		TiddlyWiki2MediaWikiTranslator t = new TiddlyWiki2MediaWikiTranslator();
		assertEquals("{|\n|a||b\n|}", t.translate("|a|b|"));
		assertEquals("notab\n{|\n|a||b||c\n|}\nnotab", t.translate("notab\n|a|b|c|\nnotab"));
		//two rows
		assertEquals("{|\n|a||b\n|-\n|d||e\n|}", t.translate("|a|b|\n|d|e|"));
	}
	*/

	/*
	// FIXME - failing, re-enabled later
	public void testNewLine() throws Exception {
		TiddlyWiki2MediaWikiTranslator t = new TiddlyWiki2MediaWikiTranslator();
		//if first character is letter -> <br/> included
		assertEquals("*first\n*second\n*third", t.translate("*first\\n*second\\n*third"));
	}
	*/

	public void testWikiLinks() throws Exception {
		TiddlyWiki2MediaWikiTranslator t = new TiddlyWiki2MediaWikiTranslator();
		assertEquals("abc [[WikiLink]] def", t.translate("abc WikiLink def"));
	}

	public void testInsertBreaks() throws Exception {
		TiddlyWiki2MediaWikiTranslator t = new TiddlyWiki2MediaWikiTranslator();
		//assertEquals("abc<br/>\ndef<br/>\nghi", t.translate("abc\ndef\nghi"));
	}
}
