/**
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, version 2.1, dated February 1999.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the latest version of the GNU Lesser General
 * Public License as published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program (LICENSE.txt); if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Based on code generated by Agitar build: Agitator Version 1.0.2.000071 (Build date: Jan 12, 2007) [1.0.2.000071]
 */
package org.jamwiki.migrate;

import org.jamwiki.model.WikiUser;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 */
public class MediaWikiXmlTopicFactoryTest {

	/**
	 *
	 */
	@Test(expected=NullPointerException.class)
	public void testCharactersThrowsNullPointerException() throws Throwable {
		char[] buf = new char[1];
		MediaWikiXmlTopicFactory MediaWikiXmlTopicFactory = new MediaWikiXmlTopicFactory("testMediaWikiXmlTopicFactoryVirtualWiki", new WikiUser(), "testMediaWikiXmlTopicFactoryAuthorIpAddress");
		MediaWikiXmlTopicFactory.characters(buf, 100, 1000);
	}

	/**
	 *
	 */
	@Test(expected=NullPointerException.class)
	public void testEndElementThrowsNullPointerException1() throws Throwable {
		MediaWikiXmlTopicFactory MediaWikiXmlTopicFactory = new MediaWikiXmlTopicFactory("testMediaWikiXmlTopicFactoryVirtualWiki", new WikiUser(), "testMediaWikiXmlTopicFactoryAuthorIpAddress");
		MediaWikiXmlTopicFactory.endElement("testMediaWikiXmlTopicFactoryNamespaceURI", "testMediaWikiXmlTopicFactorySName", "title");
	}

	/**
	 *
	 */
	@Test(expected=NullPointerException.class)
	public void testEndElementThrowsNullPointerException2() throws Throwable {
		MediaWikiXmlTopicFactory MediaWikiXmlTopicFactory = new MediaWikiXmlTopicFactory("testMediaWikiXmlTopicFactoryVirtualWiki", new WikiUser(""), "testMediaWikiXmlTopicFactoryAuthorIpAddress");
		MediaWikiXmlTopicFactory.endElement("testMediaWikiXmlTopicFactoryNamespaceURI", "testMediaWikiXmlTopicFactorySName", "page");
	}

	/**
	 *
	 */
	@Test(expected=NullPointerException.class)
	public void testEndElementThrowsNullPointerException3() throws Throwable {
		MediaWikiXmlTopicFactory MediaWikiXmlTopicFactory = new MediaWikiXmlTopicFactory("testMediaWikiXmlTopicFactoryVirtualWiki", new WikiUser(""), "testMediaWikiXmlTopicFactoryAuthorIpAddress");
		MediaWikiXmlTopicFactory.endElement("testMediaWikiXmlTopicFactoryNamespaceURI", "testMediaWikiXmlTopicFactorySName", "text");
	}

	/**
	 *
	 */
	@Test(expected=NullPointerException.class)
	public void testEndElementThrowsNullPointerException4() throws Throwable {
		MediaWikiXmlTopicFactory MediaWikiXmlTopicFactory = new MediaWikiXmlTopicFactory("testMediaWikiXmlTopicFactoryVirtualWiki", new WikiUser(""), "testMediaWikiXmlTopicFactoryAuthorIpAddress");
		MediaWikiXmlTopicFactory.endElement("testMediaWikiXmlTopicFactoryNamespaceURI", "testMediaWikiXmlTopicFactorySName", "namespace");
	}
}

