/**
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, version 2.1, dated February 1999.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the latest version of the GNU Lesser General
 * Public License as published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program (LICENSE.txt); if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Based on code generated by Agitar build: Agitator Version 1.0.2.000071 (Build date: Jan 12, 2007) [1.0.2.000071]
 */
package org.jamwiki.test.utils;

import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import java.util.Properties;
import junit.framework.TestCase;
import org.jamwiki.utils.SortedProperties;

/**
 *
 */
public class SortedPropertiesTest extends TestCase {

	/**
	 *
	 */
	public void testConstructor() throws Throwable {
		Properties properties = new SortedProperties();
		new SortedProperties(properties);
		assertEquals("(SortedProperties) properties.size()", 0, properties.size());
	}

	/**
	 *
	 */
	public void testKeys() throws Throwable {
		// FIXME - implement
	}

	/**
	 *
	 */
	public void testConstructorThrowsNullPointerException() throws Throwable {
		try {
			new SortedProperties(null);
			fail("Expected NullPointerException to be thrown");
		} catch (NullPointerException ex) {
			assertNull("ex.getMessage()", ex.getMessage());
		}
	}
}

